# Workflow Name
name: Build
# Configure Triggers
on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - "CHANGELOG.md"
      - "version.txt"
      - ".github/**"
  release:
    types: [published]
env:
  SERVICE_NAME: python-demo-semantic
  PYTHON_VERSION: "3.9.6"
  POETRY_VERSION: "1.1.8"
# Configure Jobs
jobs:
  build:
    name: Docker Build and Push
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      # Workaround for running composite actions from private repo
      - name: Get composite run steps repository
        uses: actions/checkout@v2
        with:
          repository: jonyjalfon94/workflow-templates
          token: ${{ secrets.TOKEN }}
          path: .github

      # Get current date to pass as build-arg
      - name: Get current date
        shell: bash
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%dT%H:%M:%S)"

      # Build and Push with Docker
      - uses: ./.github/actions/build-and-push-docker-2
        name: Build and Push Docker Image
        with:
          push: true
          target: production
          github_token: ${{ secrets.token }}
          docker_username: jonyjalfon94
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image_name: ${{ env.SERVICE_NAME }}
          build_args: |
            SERVICE_COMMIT=${{ github.sha }}
            SERVICE_NAME=${{ env.SERVICE_NAME }}
            SERVICE_VERSION=${{ github.sha }}
            SERVICE_BUILD_TIME=${{ steps.date.outputs.date }}

      # Workaround for post action error
      - name: Get composite run steps repository
        uses: actions/checkout@v2
        with:
          repository: jonyjalfon94/workflow-templates
          token: ${{ secrets.TOKEN }}
          path: .github
