
# Workflow Name
name: CI
# Configure Triggers
on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'CHANGELOG.md'
      - '.github/**'
  pull_request:
    branches: [ main, develop ]

env:
  SERVICE_NAME: python-demo-2
  PYTHON_VERSION: "3.9.6"
  POETRY_VERSION: "1.1.8"
# Configure Jobs
jobs:
  test:
    uses: jonyjalfon94/workflow-templates/.github/workflows/ci-docker.yml@main
